GET http://localhost:5109/products/get

###

GET http://localhost:5109/products/random

###

POST http://localhost:5109/products
Content-Type: application/json

{
    "Name": "Solna Zupa",
    "Kcal": 40,
    "Carbo": 10.0,
    "Fat": 3.2,
    "Proteins": 5.2,
    "Salt": 5.2,
    "Sugar": 2.2,
    "CategoryId": 1
}

###

PUT http://localhost:5109/products/2
Content-Type: application/json

{
    "Name": "Ciastko",
    "Kcal": 400,
    "Carbo": 10.0,
    "Fat": 50,
    "Proteins": 5.2,
    "Salt": 0.2,
    "Sugar": 2.2,
    "CategoryId": 1
}

###
DELETE http://localhost:5109/products/3