GET http://localhost:5109/products

###

GET http://localhost:5109/products/1

###

POST http://localhost:5109/products
Content-Type: application/json

{
    "Name": "Banan",
    "Kcal": 40,
    "Carbo": 10.0,
    "Fat": 3.2,
    "Proteins": 5.2,
    "Salt": 0.2,
    "Sugar": 2.2,
    "CategoryId": 1
}

###

PUT http://localhost:5109/products/5
Content-Type: application/json

{
    "Name": "Ciastko",
    "Kcal": 400,
    "Carbo": 10.0,
    "Fat": 3.2,
    "Proteins": 5.2,
    "Salt": 0.2,
    "Sugar": 2.2,
    "CategoryId": 1
}

###
DELETE http://localhost:5109/products/4