// <auto-generated />
using Gulbee.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gulbee.Api.Data.Migrations
{
    [DbContext(typeof(GulbeeContext))]
    [Migration("20241006101302_ChatGPTData")]
    partial class ChatGPTData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Gulbee.Api.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Owoce"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Nabiał"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Warzywa"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mięso"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Zboża"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Fast Food"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Oleje"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Gotowce"
                        });
                });

            modelBuilder.Entity("Gulbee.Api.Entities.Nutri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Carbo")
                        .HasColumnType("REAL");

                    b.Property<double>("Fat")
                        .HasColumnType("REAL");

                    b.Property<double>("Fiber")
                        .HasColumnType("REAL");

                    b.Property<double>("Proteins")
                        .HasColumnType("REAL");

                    b.Property<double>("Salt")
                        .HasColumnType("REAL");

                    b.Property<double>("Sugar")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Nutritions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Carbo = 22.84,
                            Fat = 0.33000000000000002,
                            Fiber = 2.0,
                            Proteins = 1.0900000000000001,
                            Salt = 0.0,
                            Sugar = 12.23
                        },
                        new
                        {
                            Id = 2,
                            Carbo = 1.28,
                            Fat = 33.140000000000001,
                            Fiber = 0.0,
                            Proteins = 24.899999999999999,
                            Salt = 1.8,
                            Sugar = 0.5
                        },
                        new
                        {
                            Id = 3,
                            Carbo = 9.5800000000000001,
                            Fat = 0.23999999999999999,
                            Fiber = 1.5,
                            Proteins = 0.93000000000000005,
                            Salt = 0.0,
                            Sugar = 4.7400000000000002
                        },
                        new
                        {
                            Id = 4,
                            Carbo = 0.0,
                            Fat = 13.6,
                            Fiber = 0.0,
                            Proteins = 27.300000000000001,
                            Salt = 0.10000000000000001,
                            Sugar = 0.0
                        },
                        new
                        {
                            Id = 5,
                            Carbo = 43.299999999999997,
                            Fat = 4.2000000000000002,
                            Fiber = 5.0,
                            Proteins = 8.8000000000000007,
                            Salt = 0.5,
                            Sugar = 6.0
                        },
                        new
                        {
                            Id = 6,
                            Carbo = 30.0,
                            Fat = 15.0,
                            Fiber = 2.0,
                            Proteins = 17.0,
                            Salt = 1.0,
                            Sugar = 5.0
                        },
                        new
                        {
                            Id = 7,
                            Carbo = 0.0,
                            Fat = 100.0,
                            Fiber = 0.0,
                            Proteins = 0.0,
                            Salt = 0.0,
                            Sugar = 0.0
                        },
                        new
                        {
                            Id = 8,
                            Carbo = 44.0,
                            Fat = 6.0,
                            Fiber = 1.0,
                            Proteins = 5.0,
                            Salt = 1.5,
                            Sugar = 2.0
                        },
                        new
                        {
                            Id = 9,
                            Carbo = 13.81,
                            Fat = 0.17000000000000001,
                            Fiber = 0.80000000000000004,
                            Proteins = 0.26000000000000001,
                            Salt = 0.0,
                            Sugar = 10.390000000000001
                        },
                        new
                        {
                            Id = 10,
                            Carbo = 3.6000000000000001,
                            Fat = 3.2999999999999998,
                            Fiber = 0.5,
                            Proteins = 10.0,
                            Salt = 0.10000000000000001,
                            Sugar = 4.7000000000000002
                        },
                        new
                        {
                            Id = 11,
                            Carbo = 15.23,
                            Fat = 0.14000000000000001,
                            Fiber = 0.69999999999999996,
                            Proteins = 0.35999999999999999,
                            Salt = 0.0,
                            Sugar = 9.75
                        },
                        new
                        {
                            Id = 12,
                            Carbo = 3.3799999999999999,
                            Fat = 4.2999999999999998,
                            Fiber = 1.2,
                            Proteins = 11.119999999999999,
                            Salt = 0.59999999999999998,
                            Sugar = 2.7000000000000002
                        },
                        new
                        {
                            Id = 13,
                            Carbo = 3.9199999999999999,
                            Fat = 0.20000000000000001,
                            Fiber = 1.0,
                            Proteins = 0.88,
                            Salt = 0.0,
                            Sugar = 2.6299999999999999
                        },
                        new
                        {
                            Id = 14,
                            Carbo = 0.0,
                            Fat = 15.0,
                            Fiber = 0.0,
                            Proteins = 26.0,
                            Salt = 0.10000000000000001,
                            Sugar = 0.0
                        },
                        new
                        {
                            Id = 15,
                            Carbo = 30.449999999999999,
                            Fat = 1.5,
                            Fiber = 2.2999999999999998,
                            Proteins = 6.0,
                            Salt = 0.10000000000000001,
                            Sugar = 1.1000000000000001
                        },
                        new
                        {
                            Id = 16,
                            Carbo = 33.329999999999998,
                            Fat = 10.0,
                            Fiber = 4.0,
                            Proteins = 11.0,
                            Salt = 1.0,
                            Sugar = 3.0
                        },
                        new
                        {
                            Id = 17,
                            Carbo = 0.0,
                            Fat = 100.0,
                            Fiber = 0.0,
                            Proteins = 0.0,
                            Salt = 0.0,
                            Sugar = 0.0
                        },
                        new
                        {
                            Id = 18,
                            Carbo = 39.0,
                            Fat = 3.0,
                            Fiber = 3.5,
                            Proteins = 6.0,
                            Salt = 1.5,
                            Sugar = 2.0
                        },
                        new
                        {
                            Id = 19,
                            Carbo = 11.94,
                            Fat = 0.65000000000000002,
                            Fiber = 1.6000000000000001,
                            Proteins = 1.2,
                            Salt = 0.0,
                            Sugar = 4.4199999999999999
                        },
                        new
                        {
                            Id = 20,
                            Carbo = 3.3999999999999999,
                            Fat = 0.29999999999999999,
                            Fiber = 1.0,
                            Proteins = 16.0,
                            Salt = 0.5,
                            Sugar = 2.7000000000000002
                        },
                        new
                        {
                            Id = 21,
                            Carbo = 6.0300000000000002,
                            Fat = 0.29999999999999999,
                            Fiber = 0.59999999999999998,
                            Proteins = 1.0,
                            Salt = 0.0,
                            Sugar = 4.2000000000000002
                        },
                        new
                        {
                            Id = 22,
                            Carbo = 1.5,
                            Fat = 5.5,
                            Fiber = 1.1000000000000001,
                            Proteins = 20.0,
                            Salt = 1.5,
                            Sugar = 1.0
                        },
                        new
                        {
                            Id = 23,
                            Carbo = 71.5,
                            Fat = 3.1000000000000001,
                            Fiber = 5.2000000000000002,
                            Proteins = 13.300000000000001,
                            Salt = 0.10000000000000001,
                            Sugar = 0.90000000000000002
                        },
                        new
                        {
                            Id = 24,
                            Carbo = 41.399999999999999,
                            Fat = 15.0,
                            Fiber = 2.5,
                            Proteins = 3.3999999999999999,
                            Salt = 1.3,
                            Sugar = 0.40000000000000002
                        },
                        new
                        {
                            Id = 25,
                            Carbo = 0.0,
                            Fat = 100.0,
                            Fiber = 0.0,
                            Proteins = 0.0,
                            Salt = 0.0,
                            Sugar = 0.0
                        },
                        new
                        {
                            Id = 26,
                            Carbo = 30.0,
                            Fat = 12.0,
                            Fiber = 1.8999999999999999,
                            Proteins = 15.0,
                            Salt = 1.8,
                            Sugar = 3.5
                        },
                        new
                        {
                            Id = 27,
                            Carbo = 7.6799999999999997,
                            Fat = 0.29999999999999999,
                            Fiber = 1.2,
                            Proteins = 0.67000000000000004,
                            Salt = 0.0,
                            Sugar = 4.8899999999999997
                        },
                        new
                        {
                            Id = 28,
                            Carbo = 4.9900000000000002,
                            Fat = 0.97999999999999998,
                            Fiber = 0.40000000000000002,
                            Proteins = 3.3999999999999999,
                            Salt = 0.10000000000000001,
                            Sugar = 5.0
                        },
                        new
                        {
                            Id = 29,
                            Carbo = 2.1600000000000001,
                            Fat = 0.16,
                            Fiber = 0.29999999999999999,
                            Proteins = 0.65000000000000002,
                            Salt = 0.0,
                            Sugar = 1.3799999999999999
                        },
                        new
                        {
                            Id = 30,
                            Carbo = 1.4299999999999999,
                            Fat = 42.0,
                            Fiber = 0.0,
                            Proteins = 37.0,
                            Salt = 1.8,
                            Sugar = 0.45000000000000001
                        },
                        new
                        {
                            Id = 31,
                            Carbo = 14.07,
                            Fat = 0.33000000000000002,
                            Fiber = 1.5,
                            Proteins = 0.81000000000000005,
                            Salt = 0.0,
                            Sugar = 10.02
                        },
                        new
                        {
                            Id = 32,
                            Carbo = 1.7,
                            Fat = 7.0,
                            Fiber = 0.0,
                            Proteins = 20.0,
                            Salt = 1.7,
                            Sugar = 0.5
                        },
                        new
                        {
                            Id = 33,
                            Carbo = 72.569999999999993,
                            Fat = 1.8700000000000001,
                            Fiber = 3.0,
                            Proteins = 10.67,
                            Salt = 0.01,
                            Sugar = 1.1200000000000001
                        },
                        new
                        {
                            Id = 34,
                            Carbo = 36.0,
                            Fat = 17.0,
                            Fiber = 2.3999999999999999,
                            Proteins = 10.0,
                            Salt = 1.5,
                            Sugar = 1.8
                        },
                        new
                        {
                            Id = 35,
                            Carbo = 0.0,
                            Fat = 100.0,
                            Fiber = 0.0,
                            Proteins = 0.0,
                            Salt = 0.0,
                            Sugar = 0.0
                        },
                        new
                        {
                            Id = 36,
                            Carbo = 28.0,
                            Fat = 10.0,
                            Fiber = 2.0,
                            Proteins = 16.0,
                            Salt = 2.0,
                            Sugar = 3.0
                        },
                        new
                        {
                            Id = 37,
                            Carbo = 4.8099999999999996,
                            Fat = 0.12,
                            Fiber = 1.2,
                            Proteins = 0.88,
                            Salt = 0.0,
                            Sugar = 4.7400000000000002
                        },
                        new
                        {
                            Id = 38,
                            Carbo = 9.6300000000000008,
                            Fat = 0.60999999999999999,
                            Fiber = 0.80000000000000004,
                            Proteins = 1.1499999999999999,
                            Salt = 0.0,
                            Sugar = 5.4100000000000001
                        },
                        new
                        {
                            Id = 39,
                            Carbo = 10.449999999999999,
                            Fat = 0.12,
                            Fiber = 1.6000000000000001,
                            Proteins = 0.91000000000000003,
                            Salt = 0.01,
                            Sugar = 9.0999999999999996
                        },
                        new
                        {
                            Id = 40,
                            Carbo = 2.0,
                            Fat = 48.0,
                            Fiber = 0.0,
                            Proteins = 30.0,
                            Salt = 2.5,
                            Sugar = 0.69999999999999996
                        });
                });

            modelBuilder.Entity("Gulbee.Api.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kcal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NutriId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("NutriId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Kcal = 89,
                            Name = "Banan",
                            NutriId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Kcal = 402,
                            Name = "Ser Cheddar",
                            NutriId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Kcal = 41,
                            Name = "Marchew",
                            NutriId = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Kcal = 239,
                            Name = "Kurczak",
                            NutriId = 4
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Kcal = 246,
                            Name = "Chleb pełnoziarnisty",
                            NutriId = 5
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Kcal = 295,
                            Name = "Burger",
                            NutriId = 6
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            Kcal = 884,
                            Name = "Oliwa z oliwek",
                            NutriId = 7
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 8,
                            Kcal = 240,
                            Name = "Zupa instant",
                            NutriId = 8
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Kcal = 52,
                            Name = "Jabłko",
                            NutriId = 9
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Kcal = 59,
                            Name = "Jogurt naturalny",
                            NutriId = 10
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Kcal = 57,
                            Name = "Gruszka",
                            NutriId = 11
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Kcal = 98,
                            Name = "Serek wiejski",
                            NutriId = 12
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Kcal = 18,
                            Name = "Pomidor",
                            NutriId = 13
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Kcal = 250,
                            Name = "Wołowina",
                            NutriId = 14
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Kcal = 157,
                            Name = "Makaron pełnoziarnisty",
                            NutriId = 15
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            Kcal = 266,
                            Name = "Pizza",
                            NutriId = 16
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 7,
                            Kcal = 862,
                            Name = "Olej kokosowy",
                            NutriId = 17
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 8,
                            Kcal = 210,
                            Name = "Gotowe pierogi",
                            NutriId = 18
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            Kcal = 52,
                            Name = "Malina",
                            NutriId = 19
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Kcal = 72,
                            Name = "Twaróg chudy",
                            NutriId = 20
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Kcal = 31,
                            Name = "Papryka",
                            NutriId = 21
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Kcal = 145,
                            Name = "Szynka",
                            NutriId = 22
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            Kcal = 343,
                            Name = "Kasza gryczana",
                            NutriId = 23
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 6,
                            Kcal = 312,
                            Name = "Frytki",
                            NutriId = 24
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 7,
                            Kcal = 884,
                            Name = "Olej rzepakowy",
                            NutriId = 25
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 8,
                            Kcal = 300,
                            Name = "Gotowa lasagna",
                            NutriId = 26
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            Kcal = 32,
                            Name = "Truskawka",
                            NutriId = 27
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            Kcal = 42,
                            Name = "Mleko",
                            NutriId = 28
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Kcal = 12,
                            Name = "Ogórek",
                            NutriId = 29
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 4,
                            Kcal = 541,
                            Name = "Boczek",
                            NutriId = 30
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 1,
                            Kcal = 60,
                            Name = "Brzoskwinia",
                            NutriId = 31
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            Kcal = 65,
                            Name = "Kefir",
                            NutriId = 32
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 5,
                            Kcal = 360,
                            Name = "Ryż brązowy",
                            NutriId = 33
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 6,
                            Kcal = 295,
                            Name = "Hamburger",
                            NutriId = 34
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 7,
                            Kcal = 884,
                            Name = "Olej lniany",
                            NutriId = 35
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 8,
                            Kcal = 260,
                            Name = "Gotowa pizza",
                            NutriId = 36
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 1,
                            Kcal = 50,
                            Name = "Czereśnia",
                            NutriId = 37
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 2,
                            Kcal = 61,
                            Name = "Jogurt naturalny",
                            NutriId = 38
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 1,
                            Kcal = 47,
                            Name = "Pomarańcza",
                            NutriId = 39
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            Kcal = 500,
                            Name = "Kabanos",
                            NutriId = 40
                        });
                });

            modelBuilder.Entity("Gulbee.Api.Entities.Product", b =>
                {
                    b.HasOne("Gulbee.Api.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gulbee.Api.Entities.Nutri", "Nutri")
                        .WithMany()
                        .HasForeignKey("NutriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Nutri");
                });
#pragma warning restore 612, 618
        }
    }
}
